In [16]:
#Installation of Numpy
#!pip install numpy

In [17]:
import numpy as np

In [19]:
#! Conda list

In [20]:
a = np.array(100)
print (a)

100


In [21]:
# creating a scalar value 
a = np.array(100)
print (type(a))
print (a)

<class 'numpy.ndarray'>
100


In [22]:
# creating a vector value 
b = np.array([1,2,3,4,5])
print (type(b))
b

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [24]:
# Creating a matrix 
m = np.matrix([[1,2,3],[4,5,6]])
print (m)
print (type(m))
m.ndim

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


2

In [25]:
# Creating a 3 dimensional array 
a = np.array ([[10,20,30],[40,50,60]])
print (type(a))
print (a)
a.ndim

<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]]


2

In [26]:
# Creating a 3 dimensional Array 
e = np.array([[[11,12,13],[32,33,31],[45,58,69]]])
print (e)
print (type (e))
e.ndim

[[[11 12 13]
  [32 33 31]
  [45 58 69]]]
<class 'numpy.ndarray'>


3

# Different ways to create the Array

In [28]:
#1) Creating an arrays with Zeros 
a = np.full((3,2),10)
a
#3 -> Rows, 2-> Colums 10-> Values inside the matrix 

array([[10, 10],
       [10, 10],
       [10, 10]])

In [29]:
#2) Creating an arrays with ones 
b = np.full((4,4),1)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
#3) Creating a Null matrix
c = np.full((5,5),0)
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
#4) Creating a Identity matrix 
d = np.eye(4,4, dtype ="int")
print (d)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [32]:
#5 ) Creating an array through randomly
a1 = np.random Sample ((2,2))
print (a1)
# Because the random sample do not accepts the shape as an argument.

SyntaxError: invalid syntax (2353414099.py, line 2)

In [33]:
#5 ) Creating an array through randomly
a2 = np.random.rand(2,2)
print (a2)

[[0.42117842 0.39511281]
 [0.26940927 0.80075152]]


In [37]:
np.random.randint(10,100,(3,5))
#10-> Start 100-> Upto and (3,5)-> Matrix 

array([[33, 34, 10, 37, 93],
       [96, 17, 69, 62, 46],
       [65, 96, 80, 43, 55]])

In [39]:
# Creating an array with numbers with decimals places 
np.random.randint(10,100,(3,4)) + np.random.sample((3,4))

array([[98.5354249 , 17.98172441, 90.06674076, 20.72497743],
       [70.54897033, 16.43582447, 14.60206773, 74.6916459 ],
       [53.33972739, 59.57261139, 93.79002136, 74.06819236]])

In [40]:
# Creating an array with numbers with only 2 decimal places 
random_array = np.random.rand(4, 5).round(2)
random_array

array([[0.01, 0.05, 0.68, 0.59, 0.5 ],
       [0.62, 0.26, 0.29, 0.84, 0.38],
       [0.41, 0.89, 0.54, 0.45, 0.51],
       [0.91, 0.98, 0.02, 0.01, 0.51]])

In [41]:
list (range(11,26))
#Default Interval value will be 1. It will not consider the final value. 

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

In [42]:
# list (range (10,100,5)) --> (Start, End, Interval)
list (range (10,100,5))

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [43]:
# 1D array
np.arange (10,25)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
# 2D array 
np.arange (15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
# 2D array -> Reshaping 
np.arange (15).reshape ((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
np.arange (10,100,5).reshape ((3,6))
#10-> Start 100-> End (3,6) -> Matrix

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [50]:
np.arange (10,50,5).reshape((2,4))

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [51]:
# We can do the transpose of the matrix here..
np.arange (10,56,4).reshape((3,4)).T
# It will convert the matrix from 3*4 to 4*3

array([[10, 26, 42],
       [14, 30, 46],
       [18, 34, 50],
       [22, 38, 54]])

In [53]:
np.arange (10,56,4).reshape((3,4))
# It will convert the matrix from 3*4 to 4*3

array([[10, 14, 18, 22],
       [26, 30, 34, 38],
       [42, 46, 50, 54]])

# Creating an array using the Linspace 

In [56]:
# np.linspace (1,10,4) --> (Start, End, How Many)
# It will give the Start value, End Values, How many values need to fill between the range of values.
np.linspace (1,10,4)

array([ 1.,  4.,  7., 10.])

In [57]:
#Linspace with only integer values
np.linspace (1,10,4, dtype="int")

array([ 1,  4,  7, 10])

In [58]:
np.linspace (1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [59]:
np.linspace (10,100, 2)

array([ 10., 100.])

In [60]:
np.linspace (10,10,1)

array([10.])

# Indexing and Slicing 

In [61]:
a = np.random.randint(10,100,(5,5))
a

array([[92, 14, 36, 78, 22],
       [34, 47, 45, 26, 20],
       [46, 49, 26, 51, 84],
       [18, 88, 69, 99, 41],
       [39, 62, 63, 89, 67]])

In [62]:
a[0]

array([92, 14, 36, 78, 22])

In [63]:
a[2]

array([46, 49, 26, 51, 84])

In [64]:
l = list (range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
l[8]

9

In [66]:
 l [3]

4

In [67]:
# ALL THE ROWS and COLUMNS 
a [:,:]

array([[92, 14, 36, 78, 22],
       [34, 47, 45, 26, 20],
       [46, 49, 26, 51, 84],
       [18, 88, 69, 99, 41],
       [39, 62, 63, 89, 67]])

In [68]:
# a [:,:] --> [Start row : End row, Start column : End Columns]

In [70]:
a

array([[92, 14, 36, 78, 22],
       [34, 47, 45, 26, 20],
       [46, 49, 26, 51, 84],
       [18, 88, 69, 99, 41],
       [39, 62, 63, 89, 67]])

In [69]:
# 1) Accesing the entire first column.
a [:,0]

array([92, 34, 46, 18, 39])

In [71]:
# 2) Accesing the entire fourth column.
a [:, 3]

array([78, 26, 51, 99, 89])

In [72]:
# 3) Accesing the entire second row.
a [3:,:]

array([[18, 88, 69, 99, 41],
       [39, 62, 63, 89, 67]])

In [73]:
# 4) Fetch everything from 1St row 
a [1:,:]

array([[34, 47, 45, 26, 20],
       [46, 49, 26, 51, 84],
       [18, 88, 69, 99, 41],
       [39, 62, 63, 89, 67]])

In [80]:
# 5) Fetch everything from 2nd column 
a [:,2:]

array([[36, 78, 22],
       [45, 26, 20],
       [26, 51, 84],
       [69, 99, 41],
       [63, 89, 67]])

In [82]:
# 6) fetch everything from the 1st Row and 3rd Column 
a [1:, 3:]

array([[26, 20],
       [51, 84],
       [99, 41],
       [89, 67]])

In [76]:
# 7) Fetch values from the 1st row and till the 2nd column 
a [1:,:2]

array([[34, 47],
       [46, 49],
       [18, 88],
       [39, 62]])

In [86]:
# 8) Fetch values from the 2nd row and till the 3rd column 
a [2:,:3]

array([[46, 49, 26],
       [18, 88, 69],
       [39, 62, 63]])

In [87]:
# 9) Fetch the value from the 1st row and only 3rd column 
a [1:, :3]

array([[34, 47, 45],
       [46, 49, 26],
       [18, 88, 69],
       [39, 62, 63]])

# NON-SEQUENTIAL VALUES..


In [83]:
a

array([[92, 14, 36, 78, 22],
       [34, 47, 45, 26, 20],
       [46, 49, 26, 51, 84],
       [18, 88, 69, 99, 41],
       [39, 62, 63, 89, 67]])

In [88]:
# 10) Fetching the values from the 0th&2nd Row and from all the columns 
a [[0,2], :]

array([[92, 14, 36, 78, 22],
       [46, 49, 26, 51, 84]])

In [89]:
# 11) Fetching the values from the 0&2nd Row and of 1st and 3rd columns
a [[0,2],[1,3]]

array([14, 51])

In [90]:
# 12) Fetching the values from the 1st&3rd Row and 2nd&4th columns
a [[1,2], [2,4]]

array([45, 84])

In [91]:
# 13) Fetching the values from the 0&2 rows and 1&4 columns
a [[0,2],[1,4]]

array([14, 84])

In [92]:
# 14) Fetching the values from the all the rows and all the columns
a [:,:]

array([[92, 14, 36, 78, 22],
       [34, 47, 45, 26, 20],
       [46, 49, 26, 51, 84],
       [18, 88, 69, 99, 41],
       [39, 62, 63, 89, 67]])

# Boolean Indexing 

In [93]:
a = np.random.randint (10,100,(4,5))
a

array([[94, 44, 80, 56, 78],
       [44, 99, 61, 29, 53],
       [26, 87, 30, 88, 19],
       [59, 74, 56, 61, 81]])

In [94]:
a > 80

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False,  True, False],
       [False, False, False, False,  True]])

In [95]:
a [a>70]

array([94, 80, 78, 99, 87, 88, 74, 81])

In [96]:
a [2,3] >0

True

In [97]:
a [3,4] >20

True

In [98]:
# Generating the values based on the multiple conditions 
a [(a>=50) & (a<= 90)]

array([80, 56, 78, 61, 53, 87, 88, 59, 74, 56, 61, 81])

In [99]:
a [(a>60) | (a<90)]

array([94, 44, 80, 56, 78, 44, 99, 61, 29, 53, 26, 87, 30, 88, 19, 59, 74,
       56, 61, 81])

# Sorting 

In [100]:
# Sorting is used to sort the data in a particular order
sorted (a [(a>=50) & (a<= 90)])

[53, 56, 56, 59, 61, 61, 74, 78, 80, 81, 87, 88]

In [101]:
# By default, The sorting will be take from the Ascending order..

In [102]:
sorted (a[a%2 == 0])
# default it will be in the ascending order.

[26, 30, 44, 44, 56, 56, 74, 78, 80, 88, 94]

In [105]:
sorted (a[a%2 == 0], reverse= True)
#reverse=True -> It will convert from ascending to descending order. 

[94, 88, 80, 78, 74, 56, 56, 44, 44, 30, 26]

In [110]:
# Genearting the binaries from the Boolean
np.multiply (a>50,1)

array([[1, 0, 1, 1, 1],
       [0, 1, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1]])

In [111]:
np.multiply (a<50,1)

array([[0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0]])

In [112]:
oned = np.linspace (10,35,9, dtype = "int")
oned

array([10, 13, 16, 19, 22, 25, 28, 31, 35])

In [113]:
a = np.random.randint(10,100,(4,5))
a

array([[59, 59, 93, 55, 67],
       [94, 79, 93, 43, 63],
       [79, 30, 44, 12, 70],
       [32, 12, 96, 42, 52]])

In [114]:
# To find the Shape of the matrix 
a.shape

(4, 5)

In [115]:
# To find the Size of the matrix 
a.size


20

In [116]:
oned

array([10, 13, 16, 19, 22, 25, 28, 31, 35])

In [117]:
oned + 10 

array([20, 23, 26, 29, 32, 35, 38, 41, 45])

In [118]:
oned - 12 

array([-2,  1,  4,  7, 10, 13, 16, 19, 23])

In [119]:
oned * 12 

array([120, 156, 192, 228, 264, 300, 336, 372, 420])

In [120]:
oned /12 

array([0.83333333, 1.08333333, 1.33333333, 1.58333333, 1.83333333,
       2.08333333, 2.33333333, 2.58333333, 2.91666667])

In [121]:
oned //2 

array([ 5,  6,  8,  9, 11, 12, 14, 15, 17], dtype=int32)

In [122]:
oned ** 2

array([ 100,  169,  256,  361,  484,  625,  784,  961, 1225], dtype=int32)

In [123]:
oned % 2 

array([0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=int32)

# Aggregation Operations 

In [124]:
a = oned 
a

array([10, 13, 16, 19, 22, 25, 28, 31, 35])

In [127]:
a.sum

<function ndarray.sum>

In [126]:
oned.mean

<function ndarray.mean>

# Axis-Wise Operations :


In [128]:
# Here Axis = 0 means Column ans Axis = 1 means Row 
array = np.random.randint(10,100,(4,5))
array

array([[81, 87, 90, 13, 73],
       [18, 69, 30, 66, 96],
       [56, 86, 49, 74, 64],
       [71, 46, 62, 92, 93]])

In [130]:
mat = np.matrix(array)
mat

matrix([[81, 87, 90, 13, 73],
        [18, 69, 30, 66, 96],
        [56, 86, 49, 74, 64],
        [71, 46, 62, 92, 93]])

In [131]:
vec = np.linspace(10,35,9,dtype = "int")
vec

array([10, 13, 16, 19, 22, 25, 28, 31, 35])

In [132]:
vec -12 


array([-2,  1,  4,  7, 10, 13, 16, 19, 23])

In [133]:
mat = np.matrix(array)
mat

matrix([[81, 87, 90, 13, 73],
        [18, 69, 30, 66, 96],
        [56, 86, 49, 74, 64],
        [71, 46, 62, 92, 93]])

In [134]:
mat

matrix([[81, 87, 90, 13, 73],
        [18, 69, 30, 66, 96],
        [56, 86, 49, 74, 64],
        [71, 46, 62, 92, 93]])

In [135]:
array

array([[81, 87, 90, 13, 73],
       [18, 69, 30, 66, 96],
       [56, 86, 49, 74, 64],
       [71, 46, 62, 92, 93]])

In [136]:
vec.sum()

199

In [137]:
mat.sum()

1316

In [138]:
array.sum()

1316

In [139]:
array.max()

96

In [140]:
array.min()

13

In [141]:
array.size

20

In [142]:
array.mean()


65.8

In [143]:
np.quantile (array, 0.25)

54.25

In [144]:
np.quantile (array, 0.5)

70.0

In [145]:
array[0].sum()

344

In [146]:
# Performing Aggregation Operation on the Row or Column 
array [:,4].sum()

326

# Axis = 0 means Column and Axis = 1 means Row 

In [147]:
array.sum (axis = 0)

array([226, 288, 231, 245, 326])

In [148]:
array.sum (axis = 1)

array([344, 279, 329, 364])

In [149]:
array.mean(axis = 0)

array([56.5 , 72.  , 57.75, 61.25, 81.5 ])

# Aggregations Functions 

# 1)Sum # 2)Count # 3)min # 4)max 
# 5)std.s --> Standard Deviation Sample 
# 6)std.p --> Standard Deviation Populations 
# 7)var.p --> Variance Sample 
# 8)var.s --> Variance Population 
# 9)Percentage # 10)Percentile # 11)Average 

In [152]:
array.mean(axis = 1)

array([68.8, 55.8, 65.8, 72.8])

# Matrix Addition 

In [153]:
array 

array([[81, 87, 90, 13, 73],
       [18, 69, 30, 66, 96],
       [56, 86, 49, 74, 64],
       [71, 46, 62, 92, 93]])

In [154]:
array2 = np.random.randint(1,10,(4,5))
array2

array([[2, 6, 3, 5, 8],
       [2, 7, 8, 3, 5],
       [2, 4, 2, 3, 8],
       [1, 8, 6, 8, 6]])

In [156]:
array + array2
#Concatination

array([[ 83,  93,  93,  18,  81],
       [ 20,  76,  38,  69, 101],
       [ 58,  90,  51,  77,  72],
       [ 72,  54,  68, 100,  99]])

# Matrix Multification 

In [157]:
a = np.matrix(np.random.randint (1,10,(3,4)))
a

matrix([[3, 1, 6, 1],
        [5, 1, 1, 9],
        [3, 5, 4, 9]])

In [158]:
b = np.matrix(np.random.randint (1,10,(4,3)))
b

matrix([[1, 3, 2],
        [5, 7, 4],
        [8, 1, 3],
        [8, 1, 5]])

In [159]:
a*b

matrix([[ 64,  23,  33],
        [ 90,  32,  62],
        [132,  57,  83]])

# Advantages of the Arrays:
#1) Arrays are very faster than lists.
#2) Arrays consumes lesser memory than lists

# Advantages of the List:
#1) Lists are Heterogenous 
#2) List can be easily modify..

# Splitting of the Arrays 

In [160]:
a = np.random.randint(1,10,(4,5))
a

array([[4, 5, 6, 7, 6],
       [8, 5, 6, 7, 1],
       [8, 7, 7, 5, 6],
       [1, 3, 3, 6, 1]])

In [161]:
# Splitting the Array or Matrix by Rows 
np.vsplit(a,4)

[array([[4, 5, 6, 7, 6]]),
 array([[8, 5, 6, 7, 1]]),
 array([[8, 7, 7, 5, 6]]),
 array([[1, 3, 3, 6, 1]])]

In [162]:
# Splitting of the Array or Matrix by Columns 
np.hsplit(a,5)

[array([[4],
        [8],
        [8],
        [1]]),
 array([[5],
        [5],
        [7],
        [3]]),
 array([[6],
        [6],
        [7],
        [3]]),
 array([[7],
        [7],
        [5],
        [6]]),
 array([[6],
        [1],
        [6],
        [1]])]

# Concatination and Stacking 

# Concatination and Stacking 

In [163]:
a = np.matrix([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [164]:
b = np.matrix([[5,6]])
b

matrix([[5, 6]])

In [165]:
# Concatenating the a & b Matrixes 
np.concatenate((a,b))

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [166]:
# Transposing of the Matrix and Concatenating 
np.concatenate((a,b.T), axis = 1)

matrix([[1, 2, 5],
        [3, 4, 6]])

# Note : In Concatenation, Axis = 0 means Rows and Axis = 1 means Columns 